# Generated by Django 3.2.18 on 2023-04-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleganza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='author',
            new_name='Customer',
        ),
    ]
