# Generated by Django 3.2.18 on 2023-04-21 23:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleganza', '0003_booking_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Appointment',
        ),
    ]
