# Generated by Django 3.2.18 on 2023-04-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleganza', '0004_rename_booking_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Customer',
            new_name='customer',
        ),
    ]
