# Generated by Django 3.2.18 on 2023-08-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleganza', '0006_auto_20230429_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00')], default='08:00', max_length=10),
        ),
    ]
